# Generated by Django 4.1.1 on 2022-09-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField()),
                ('username_replacement', models.JSONField()),
                ('promocode_replacement', models.JSONField()),
                ('external_link', models.CharField(blank=True, max_length=100)),
                ('pin_message_link', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='channels', to='bot.bot')),
            ],
        ),
    ]
