# Generated by Django 4.1.1 on 2022-09-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=100)),
                ('enable', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.JSONField(default=list)),
                ('promocode', models.JSONField(default=list)),
                ('title', models.CharField(blank=True, default='default', max_length=100)),
                ('telegram_id', models.IntegerField()),
                ('external_link', models.CharField(blank=True, default='default', max_length=100)),
                ('pin_message_link', models.CharField(blank=True, default='default', max_length=100)),
                ('bot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='channels', to='bot.bot')),
            ],
        ),
    ]
