# Generated by Django 4.1.1 on 2022-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='link',
        ),
        migrations.AddField(
            model_name='channel',
            name='direct_link',
            field=models.CharField(blank=True, default='default_direct_link', max_length=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='external_link',
            field=models.CharField(blank=True, default='default_external_link', max_length=100),
        ),
        migrations.AddField(
            model_name='channel',
            name='pin_link',
            field=models.CharField(blank=True, default='default_pin_link', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='telegram_id',
            field=models.IntegerField(),
        ),
    ]
