# Generated by Django 4.1.1 on 2022-10-11 14:14

import bot.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='promocode_replacement',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='username_replacement',
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UsernameReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_replacements', to='bot.channel')),
            ],
            bases=(bot.models.ReplacementFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromocodeReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_replacements', to='bot.channel')),
            ],
            bases=(bot.models.ReplacementFieldsMixin, models.Model),
        ),
    ]
