# Generated by Django 4.1.1 on 2022-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_channel_link_channel_direct_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
        migrations.AddField(
            model_name='channel',
            name='username_alias',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='channel',
            name='direct_link',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='external_link',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='pin_link',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
    ]
