# Generated by Django 4.1.1 on 2022-10-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_remove_channel_promocode_replacement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepostChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('external_link', models.CharField(blank=True, max_length=100)),
                ('pin_message_link', models.CharField(blank=True, max_length=100)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repost_channels', to='bot.bot')),
            ],
        ),
        migrations.CreateModel(
            name='InputChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_channels', to='bot.bot')),
            ],
        ),
        migrations.AlterField(
            model_name='promocodereplacement',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_replacements', to='bot.repostchannel'),
        ),
        migrations.AlterField(
            model_name='usernamereplacement',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_replacements', to='bot.repostchannel'),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
