# Generated by Django 4.1.1 on 2022-09-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_remove_channel_name_channel_username_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='pin_link',
        ),
        migrations.AddField(
            model_name='channel',
            name='pin_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='promo_replacement',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username_alias',
            field=models.JSONField(default=list),
        ),
    ]
