# Generated by Django 4.1.1 on 2022-10-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_repostchannel_inputchannel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repostchannel',
            name='title',
        ),
    ]
