# Generated by Django 4.1.1 on 2022-09-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_channel_pin_link_channel_pin_message_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='username_alias',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='promo_replacement',
            new_name='promocode',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='direct_link',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='pin_message_id',
        ),
        migrations.AddField(
            model_name='channel',
            name='pin_message_link',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
    ]
