# Generated by Django 4.1.1 on 2022-10-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_inputchannel_telegram_id_inputchannel_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepostChannel',
            new_name='OutputChannel',
        ),
    ]
