# Generated by Django 4.1.1 on 2022-10-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_inputchannel_enabled_alter_outputchannel_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputchannel',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
