# Generated by Django 4.1.1 on 2022-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_inputchannel_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputchannel',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='outputchannel',
            name='bot',
        ),
        migrations.AddField(
            model_name='bot',
            name='input_channels',
            field=models.ManyToManyField(related_name='bots', to='bot.inputchannel'),
        ),
        migrations.AddField(
            model_name='inputchannel',
            name='output_channels',
            field=models.ManyToManyField(related_name='input_channels', to='bot.outputchannel'),
        ),
    ]
