# Generated by Django 4.1.1 on 2022-10-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_inputchannel_bot_remove_outputchannel_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='input_channels',
            field=models.ManyToManyField(blank=True, related_name='bots', to='bot.inputchannel'),
        ),
        migrations.AlterField(
            model_name='inputchannel',
            name='output_channels',
            field=models.ManyToManyField(blank=True, related_name='input_channels', to='bot.outputchannel'),
        ),
    ]
