# Generated by Django 4.1.1 on 2022-10-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_bot_input_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputchannel',
            name='output_channels',
        ),
        migrations.AddField(
            model_name='bot',
            name='output_channels',
            field=models.ManyToManyField(blank=True, related_name='bots', to='bot.outputchannel'),
        ),
    ]
