# Generated by Django 4.1.1 on 2022-10-17 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_remove_inputchannel_output_channels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotChannelBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_bindings', to='bot.bot')),
                ('input_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.inputchannel')),
                ('output_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot.outputchannel')),
            ],
        ),
    ]
