# Generated by Django 4.1.1 on 2022-10-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_remove_bot_input_channels_remove_bot_output_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botchannelbinding',
            name='output_channel',
        ),
        migrations.AddField(
            model_name='botchannelbinding',
            name='output_channels',
            field=models.ManyToManyField(to='bot.outputchannel'),
        ),
    ]
