# Generated by Django 4.1.1 on 2022-10-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_remove_outputchannel_external_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botchannelbinding',
            name='input_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.inputchannel'),
        ),
        migrations.RemoveField(
            model_name='botchannelbinding',
            name='output_channels',
        ),
        migrations.AlterField(
            model_name='promocodereplacement',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_replacements', to='bot.botchannelbinding'),
        ),
        migrations.AlterField(
            model_name='usernamereplacement',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username_replacements', to='bot.botchannelbinding'),
        ),
        migrations.AddField(
            model_name='botchannelbinding',
            name='output_channels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.outputchannel'),
            preserve_default=False,
        ),
    ]
