# Generated by Django 4.1.1 on 2022-10-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_botchannelbinding_enabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='botchannelbinding',
            unique_together={('bot', 'input_channel', 'output_channel')},
        ),
    ]
